### ISSUE TITLE
binary support over bridge

### ISSUE THREAD

**Issue by max-mapper** [maxogden/electron-microscope#3]
totally doable, right now it uses `ndjson` as the serialization format, but we could add an option for binary mode

**Comment by jprichardson** [comment]
ehem... https://github.com/jprichardson/electron-ipc-stream :) I'd think it'd make your life easier. Duplex streams over IPC. Binary support out of the box :)

**Comment by max-mapper** [comment]
nice, can't use it until https://github.com/maxogden/electron-microscope/issues/2 is resolved though
