### ISSUE TITLE
Error opening app

### ISSUE THREAD

**Issue by fawadniazi** [maxogden/electron-microscope#6]
![image](https://cloud.githubusercontent.com/assets/305384/13067254/2d4a7706-d4a9-11e5-9a24-9268c0fe4f73.png)

Getting this error on windows machine.

**Comment by max-mapper** [comment]
Ahh nice catch. I just fixed it in https://github.com/maxogden/electron-microscope/commit/ce9245fb3d8565e31bc16d75c7a76f36f092bb6b

**Comment by fawadniazi** [comment]
works like a charm!
