### ISSUE TITLE
TypeError: BrowserWindow is not a constructor

### ISSUE THREAD

**Issue by tomsotte** [maxogden/electron-microscope#7]
Whenever I create a new microscope i get that error, what can I do?

**Comment by christopherfowers** [comment]
Bumping this. I'm experiencing the same thing.

**Comment by lbonillaii** [comment]
I'm getting this error as well. Any update on why and how to fix `it? This is what I got for my main.js along with the error message

```
const electron = require("electron")
const {app,BrowswerWindow} = electron

app.on('ready', () => {
  let win = new BrowswerWindow({width:800, height:600})
  win.loadURL('file://${__dirname}/index.html')
})
```
![error](https://cloud.githubusercontent.com/assets/7102177/25753178/30f0d230-3180-11e7-90a2-34904666ffaf.PNG)

**Comment by StijnDotExe** [comment]
@lbonillaii I see a few things that **could** be the cause of your error.
- Misspelling BrowserWindow
- Unnecessarily defining electron
- Not globally defining the window variable
- Possibly your loadURL statement. The version on the Electron docs is much longer, but I've found it sure to work

Try this:
```
const {app, BrowserWindow} = require("electron");
const path = require("path");
const url = require("url");
let win;

app.on('ready', () => {
  win = new BrowserWindow({width: 800, height: 600});
  win.loadURL(url.format({
    pathname: path.join(__dirname, "index.html"),
    protocol: "file:",
    slashes: true
  }));
})
```

In a VERY unlikely scenario that all of that doesn't do the trick, try defining a seperate function for creating the window. Then do this:
```app.on("ready", CreateWindow);```

Sorry for the late reply. I hope this fixes it for you!

**Comment by sayonsom** [comment]
@lbonillaii - was it just your spelling error of `BrowswerWindow` that caused this problem?
